---
- name: "6.1.3 Ensure permissions on /etc/shadow are configured (Scored)"
  file:
      dest: /etc/shadow
      owner: root
      group: root
      mode: 0000
  when: not verify|bool
  tags:
      - scored
      - cis.6.1
      - cis.6.1.3

