---
- name: "1.1.3 Ensure nodev option set on /tmp partition (Scored)"
  vars:
    tmp_mount: /lib/systemd/system/tmp.mount
  block:
    - name: "1.1.3 Ensure nodev option set in tmp.mount"
      block:
        - name: "1.1.3 register the stat output of tmp.mount"
          stat:
            path: "{{ tmp_mount }}"
          register: output_s
        - name: "1.1.3 check if option is already set"
          become: yes
          become_user: root
          ignore_errors: True
          register: presence
          shell: "grep -i 'Options' {{ tmp_mount }} | grep nodev"
          when: output_s.stat.exists == true
        - name: "1.1.3 add option if not present"
          shell: newoptions=$(grep -i 'Options' {{ tmp_mount }} |  awk '{print $1",nodev"}'); sed -i "/Options/c\\$newoptions" {{ tmp_mount }}
          when: presence is failed
        - name: "1.1.3 remount tmpfs at /tmp"
          systemd:
            state: restarted
            daemon_reload: yes
            force: yes
            name: tmp.mount
          when: presence is failed
      when:      
        - ansible_facts['service_mgr'] == "systemd"

    - name: "1.1.3 Ensure nodev option set for /tmp in fstab"
      block:
        - name: "1.1.3 register the stat output of fstab file"
          stat:
            path: /etc/fstab
          register: output_f
        - name: "1.1.3 check if option is already set"
          become: yes
          become_user: root
          ignore_errors: True
          register: presence
          shell: "grep -i ' /tmp ' /etc/fstab | grep nodev"
          when: output_f.stat.exists == true
        - name: "1.1.3 add option if not present"
          shell: newoptions=$(grep -i ' /tmp ' /etc/fstab | awk '{$4=$4",nodev"; print}'); sed -i "/ \/tmp /c\\$newoptions" /etc/fstab
          when: presence is failed
      when:
        - ansible_facts['service_mgr'] != "systemd"

   
  tags:
    - cis
    - cis.1
    - cis.1.1
    - cis.1.1.3
    - scored

