---
- include_tasks: "{{ include_task_rule }}"
  loop:
    - 1.1.1.yml
    - 1.1.2.yml
    - 1.1.3.yml
    - 1.1.4.yml
    - 1.1.5.yml
    - 1.1.15.yml
    - 1.1.16.yml
    - 1.1.17.yml
    - 1.1.21.yml
    - 1.1.22.yml
    - 1.1.23.yml
  tags:
    - cis
    - cis.1
    - scored
